//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminDCZOEM.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdminDCZOEM.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_area AS IDENTIFICADOR, nombre_area AS ÁREA, encargado AS ENCARGADO.
        /// </summary>
        internal static string AreaBusqueda {
            get {
                return ResourceManager.GetString("AreaBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre_area, encargado.
        /// </summary>
        internal static string AreaInsertar {
            get {
                return ResourceManager.GetString("AreaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_area AS &apos;ID AREA&apos;, nombre_area AS AREA, id_persona AS &apos;ID PERSONA&apos;, nombre AS NOMBRE, ap_pat AS &apos;APELLIDO PATERNO&apos;, ap_mat AS &apos;APELLIDO MATERNO&apos;.
        /// </summary>
        internal static string AreaPersonaBusqueda {
            get {
                return ResourceManager.GetString("AreaPersonaBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_area, id_persona.
        /// </summary>
        internal static string AreaPersonaInsertar {
            get {
                return ResourceManager.GetString("AreaPersonaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database=db_dczoem;Data Source=localhost;User Id=root;Password=.
        /// </summary>
        internal static string ConexionBD {
            get {
                return ResourceManager.GetString("ConexionBD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_codigo AS IDENTIFICADOR, cp AS &apos;CODIGO POSTAL&apos;, asentamiento AS ASENTAMIENTO, tipo AS TIPO, municipio AS MUNICIPIO, ciudad AS CIUDAD, estado AS ESTADO.
        /// </summary>
        internal static string CPBusqueda {
            get {
                return ResourceManager.GetString("CPBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cp, asentamiento, tipo, municipio, ciudad, estado.
        /// </summary>
        internal static string CPInsertar {
            get {
                return ResourceManager.GetString("CPInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap defaultUser {
            get {
                object obj = ResourceManager.GetObject("defaultUser", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_equipo AS IDENTIFICADOR, marca AS MARCA, serie AS SERIE, descripcion AS DESCRIPCION, id_tipo_producto AS &apos;ID TIPO PRODUCTO&apos;, tipo_producto AS &apos;TIPO DE PRODUCTO&apos;.
        /// </summary>
        internal static string EquipoBusqueda {
            get {
                return ResourceManager.GetString("EquipoBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_equipo, marca, serie, descripcion, id_tipo_producto.
        /// </summary>
        internal static string EquipoInsertar {
            get {
                return ResourceManager.GetString("EquipoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_evidencias AS IDENTIFICADOR, num_fotos AS &apos;# DE FOTOS&apos;, num_videos AS &apos;# DE VIDEOS&apos;, num_cphs AS &apos;# DE CPHS&apos;, actualizo AS ACTUALIZO, fecha AS FECHA, id_obra AS &apos;ID OBRA&apos;, nombre_obra AS OBRA.
        /// </summary>
        internal static string EvidenciasBusqueda {
            get {
                return ResourceManager.GetString("EvidenciasBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to num_fotos, num_videos, num_cphs, actualizo, id_obra.
        /// </summary>
        internal static string EvidenciasInsertar {
            get {
                return ResourceManager.GetString("EvidenciasInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Información del Sistema.
        /// </summary>
        internal static string infoWindow {
            get {
                return ResourceManager.GetString("infoWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falló al actualizar!..
        /// </summary>
        internal static string MsgActualizacionFail {
            get {
                return ResourceManager.GetString("MsgActualizacionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actualización éxitosa!..
        /// </summary>
        internal static string MsgActualizacionOk {
            get {
                return ResourceManager.GetString("MsgActualizacionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falló al buscar los datos!..
        /// </summary>
        internal static string MsgBuscarFail {
            get {
                return ResourceManager.GetString("MsgBuscarFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falló al eliminar!..
        /// </summary>
        internal static string MsgEliminacionFail {
            get {
                return ResourceManager.GetString("MsgEliminacionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminación éxitosa!..
        /// </summary>
        internal static string MsgEliminacionOk {
            get {
                return ResourceManager.GetString("MsgEliminacionOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falló al registrar!..
        /// </summary>
        internal static string MsgRegistroFail {
            get {
                return ResourceManager.GetString("MsgRegistroFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registro éxitoso!..
        /// </summary>
        internal static string MsgRegistroOk {
            get {
                return ResourceManager.GetString("MsgRegistroOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se puede eliminar el registro ya que existe una dependencia con otra tabla..
        /// </summary>
        internal static string MsgRelEliFail {
            get {
                return ResourceManager.GetString("MsgRelEliFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecciona un registro válido..
        /// </summary>
        internal static string MsgValidateRegisterSelect {
            get {
                return ResourceManager.GetString("MsgValidateRegisterSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_obra AS IDENTIFICADOR, nombre_obra AS OBRA, no_beneficiarios AS BENEFICIARIOS, id_persona &apos;ID PERSONA&apos;, nombre AS NOMBRE, ap_pat AS &apos;APELLIDO PATERNO&apos;, ap_mat AS &apos;APELLIDO MATERNO&apos;.
        /// </summary>
        internal static string ObraBusqueda {
            get {
                return ResourceManager.GetString("ObraBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre_obra, no_beneficiarios, id_persona.
        /// </summary>
        internal static string ObraInsertar {
            get {
                return ResourceManager.GetString("ObraInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ok {
            get {
                object obj = ResourceManager.GetObject("ok", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_persona AS IDENTIFICADOR, nombre AS NOMBRE, ap_pat AS &apos;APELLIDO PATERNO&apos;, ap_mat AS &apos;APELLIDO MATERNO&apos;, sexo AS SEXO, contacto AS CONTACTO, telefono1 AS TELEFONO1, telefono2 AS TELEFONO2, foto as FOTO, activo AS ACTIVO, cp AS &apos;CODIGO POSTAL&apos;, calle AS CALLE, colonia AS COLONIA, municipio AS MUNICIPIO, estado AS ESTADO, id_tipo_persona AS &apos;ID TIPO&apos;, tipo_persona AS TIPO.
        /// </summary>
        internal static string PersonaBusqueda {
            get {
                return ResourceManager.GetString("PersonaBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_persona, nombre, ap_pat, ap_mat, sexo, contacto, telefono1, telefono2, foto, activo, cp, calle, colonia, municipio, estado, id_tipo_persona.
        /// </summary>
        internal static string PersonaInsertar {
            get {
                return ResourceManager.GetString("PersonaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_responsiva AS IDENTIFICADOR, condiciones_equipo AS CONDICIONES, justificacion_salida AS JUSTIFICACION, fecha_salida AS SALIDA, fecha_a_retorno AS &apos;FECHA A RETORNO&apos;, fecha_retorno AS &apos;FECHA DE RETORNO&apos;, observ_retorno AS &apos;OBSERVACION RETORNO&apos;, id_equipo AS &apos;ID EQUIPO&apos;, marca AS MARCA, id_persona &apos;ID PERSONA&apos;, nombre AS NOMBRE, ap_pat AS &apos;APELLIDO PATERNO&apos;, ap_mat AS &apos;APELLIDO MATERNO&apos;.
        /// </summary>
        internal static string ResponsivaBusqueda {
            get {
                return ResourceManager.GetString("ResponsivaBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to condiciones_equipo, justificacion_salida, fecha_a_retorno, fecha_retorno, observ_retorno, id_equipo, id_persona.
        /// </summary>
        internal static string ResponsivaInsertar {
            get {
                return ResourceManager.GetString("ResponsivaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to area.
        /// </summary>
        internal static string tablaArea {
            get {
                return ResourceManager.GetString("tablaArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to area_persona.
        /// </summary>
        internal static string tablaAreaPersona {
            get {
                return ResourceManager.GetString("tablaAreaPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to codigo_postal.
        /// </summary>
        internal static string tablaCodigoPostal {
            get {
                return ResourceManager.GetString("tablaCodigoPostal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to equipo.
        /// </summary>
        internal static string tablaEquipo {
            get {
                return ResourceManager.GetString("tablaEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to evidencias.
        /// </summary>
        internal static string tablaEvidencias {
            get {
                return ResourceManager.GetString("tablaEvidencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to obra.
        /// </summary>
        internal static string tablaObra {
            get {
                return ResourceManager.GetString("tablaObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to persona.
        /// </summary>
        internal static string tablaPersona {
            get {
                return ResourceManager.GetString("tablaPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to responsiva.
        /// </summary>
        internal static string tablaResponsiva {
            get {
                return ResourceManager.GetString("tablaResponsiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tipo_persona.
        /// </summary>
        internal static string tablaTipoPersona {
            get {
                return ResourceManager.GetString("tablaTipoPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tipo_producto.
        /// </summary>
        internal static string tablaTipoProducto {
            get {
                return ResourceManager.GetString("tablaTipoProducto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuario.
        /// </summary>
        internal static string tablaUsuario {
            get {
                return ResourceManager.GetString("tablaUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertiente.
        /// </summary>
        internal static string tablaVertiente {
            get {
                return ResourceManager.GetString("tablaVertiente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vertiente_persona.
        /// </summary>
        internal static string tablaVertientePersona {
            get {
                return ResourceManager.GetString("tablaVertientePersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_tipo_persona AS IDENTIFICADOR, tipo_persona as TIPO.
        /// </summary>
        internal static string TipoPersonaBusqueda {
            get {
                return ResourceManager.GetString("TipoPersonaBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tipo_persona.
        /// </summary>
        internal static string TipoPersonaInsertar {
            get {
                return ResourceManager.GetString("TipoPersonaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_tipo_producto AS IDENTIFICADOR, tipo_producto as TIPO.
        /// </summary>
        internal static string TipoProductoBusqueda {
            get {
                return ResourceManager.GetString("TipoProductoBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tipo_producto.
        /// </summary>
        internal static string TipoProductoInsertar {
            get {
                return ResourceManager.GetString("TipoProductoInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap update {
            get {
                object obj = ResourceManager.GetObject("update", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_usuario AS IDENTIFICADOR, usuario AS USUARIO, contrasena AS CONTRASEÑA, id_persona AS &apos;ID PERSONA&apos;, nombre AS NOMBRE, ap_pat AS &apos;APELLIDO PATERNO&apos;, ap_mat AS &apos;APELLIDO MATERNO&apos;, tipo_persona AS &apos;TIPO&apos;.
        /// </summary>
        internal static string UsuarioBusqueda {
            get {
                return ResourceManager.GetString("UsuarioBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to usuario, contrasena, id_persona.
        /// </summary>
        internal static string UsuarioInsertar {
            get {
                return ResourceManager.GetString("UsuarioInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_vertiente AS IDENTIFICADOR, nombre_vertiente AS VERTIENTE.
        /// </summary>
        internal static string VertienteBusqueda {
            get {
                return ResourceManager.GetString("VertienteBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nombre_vertiente.
        /// </summary>
        internal static string VertienteInsertar {
            get {
                return ResourceManager.GetString("VertienteInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_vertiente AS IDENTIFICADOR, nombre_vertiente AS VERTIENTE, id_persona AS &apos;ID PERSONA&apos;, nombre AS NOMBRE, ap_pat AS &apos;APELLIDO PATERNO&apos;, ap_mat AS &apos;APELLIDO MATERNO&apos;.
        /// </summary>
        internal static string VertientePersonaBusqueda {
            get {
                return ResourceManager.GetString("VertientePersonaBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id_vertiente, id_persona.
        /// </summary>
        internal static string VertientePersonaInsertar {
            get {
                return ResourceManager.GetString("VertientePersonaInsertar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_area_persona.
        /// </summary>
        internal static string VistaAreaPersona {
            get {
                return ResourceManager.GetString("VistaAreaPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_equipo.
        /// </summary>
        internal static string VistaEquipo {
            get {
                return ResourceManager.GetString("VistaEquipo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_evidencias.
        /// </summary>
        internal static string VistaEvidencias {
            get {
                return ResourceManager.GetString("VistaEvidencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_login.
        /// </summary>
        internal static string VistaLogin {
            get {
                return ResourceManager.GetString("VistaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_obra.
        /// </summary>
        internal static string VistaObra {
            get {
                return ResourceManager.GetString("VistaObra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_persona.
        /// </summary>
        internal static string VistaPersona {
            get {
                return ResourceManager.GetString("VistaPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_responsiva.
        /// </summary>
        internal static string VistaResponsiva {
            get {
                return ResourceManager.GetString("VistaResponsiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tbl_vertiente_persona.
        /// </summary>
        internal static string VistaVertientePersona {
            get {
                return ResourceManager.GetString("VistaVertientePersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap wrong {
            get {
                object obj = ResourceManager.GetObject("wrong", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
